# Databricks locations
catalog_name: mlops_students
schema_name: sjduckersjr

# forecast horizon
horizon: 28

target: "y"

processed_features:
  num_features:
    - sell_price
    - num_events
    - is_weekend
    - day_of_week
    - day_of_month
    - week_num_year
    - week_of_month
    - day_of_month
    - year

  cat_features:
    - item_id
    - dept_id
    - cat_id
    - store_id
    - state_id

paths:
  # Path to local data
  local_sales_filepath: "data/sales_train_evaluation.csv"
  local_calendar_filepath: "data/calendar.csv"
  local_sell_prices_filepath: "data/sell_prices.csv"
  # Databricks Raw Data path
  raw_sales_path: "/Volumes/mlops_students/sjduckersjr/data/sales_train_evaluation.csv"
  raw_calendar_path: "/Volumes/mlops_students/sjduckersjr/data/calendar.csv"
  raw_sell_prices_path: "/Volumes/mlops_students/sjduckersjr/data/sell_prices.csv"